project_name: wrench
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.VERSION={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
  - image_templates:
      - "tomologic/wrench:{{ .Version }}"
      - "tomologic/wrench:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/tomologic/wrench
      - --label=org.opencontainers.image.source=https://github.com/tomologic/wrench
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=UNLICENSE
nfpms:
  - maintainer: Tomologic Ops <ops@tomologic.com>
    description: Wrench
    homepage: https://github.com/tomologic/wrench
    license: UNLICENSE
    formats:
      - deb
      - rpm
      - apk
