FROM builder

ENV PATH /go/src/github.com/tomologic/wrench:$PATH

RUN apt-get update && \
    apt-get install -y curl && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN set -x; export BATSTMP="/tmp/installbats" && \
    mkdir -p $BATSTMP && cd $BATSTMP && \
    curl -o bats.tar.gz -L https://github.com/sstephenson/bats/archive/v0.4.0.tar.gz && \
    echo "cb8a5f4c844a5f052f915036130def31140fce94  bats.tar.gz" | sha1sum -c - && \
    tar -xvf bats.tar.gz && \
    cd bats*/ && \
    bash ./install.sh /usr/local && \
    cd / && \
    rm -rf $BATSTMP
