FROM debian:jessie

RUN echo "deb http://http.debian.net/debian jessie-backports main" >> /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y git && \
    apt-get -y -t jessie-backports install "docker.io" && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ADD wrench /usr/bin/

ENTRYPOINT ["/usr/bin/wrench"]
